"""Web V2 shared API entrypoint + Payroll 3.8 installers."""
from __future__ import annotations

import vera_web_v2_api_shared as _shared
import vera_web_v2_admin_audit_archive as _audit_archive
import vera_web_v2_staff_status_sort as _staff_sort
import vera_web_v2_snapshot as _snapshot
from vera_web_v2_accumulation_permission import install_accumulation_permission
from vera_web_v2_admin_audit_archive import install_admin_audit_archive_routes
from vera_web_v2_admin_change_push import install_admin_change_push
from vera_web_v2_attendance_v42 import install_attendance_v42
from vera_web_v2_attendance_break_window import install_attendance_break_window
from vera_web_v2_attendance_break_alerts import install_attendance_break_alerts
from vera_web_v2_attendance_break_dispatch import install_attendance_break_dispatch
from vera_web_v2_attendance_policy_patch import install_attendance_policy_patch
from vera_web_v2_department_attendance import install_department_attendance_routes
from vera_web_v2_department_payroll import install_department_payroll_routes
from vera_web_v2_break_alert_control import install_break_alert_control
from vera_web_v2_break_return_penalty import install_break_return_penalty
from vera_web_v2_auto_check import install_auto_check_routes
from vera_web_v2_excel_export_style import install_excel_export_style
from vera_web_v2_leave_preview import install_leave_preview_routes
from vera_web_v2_leave_source_export import install_leave_source_export_routes
from vera_web_v2_leave_day_stats import install_leave_day_stats_routes
from vera_web_v2_leave_sync_queue import install_leave_sync_queue
from vera_web_v2_leave_violation_split import install_leave_violation_split_routes
from vera_web_v2_letan_leave_guard import install_letan_leave_guard
from vera_web_v2_long_leave_admin import install_long_leave_admin_routes
from vera_web_v2_operations_v41 import install_operations_v41
from vera_web_v2_outside_leave_rule import install_outside_leave_rule
from vera_web_v2_payroll_debt_sync import install_payroll_debt_sync_routes
from vera_web_v2_payroll_enhancements import install_payroll_enhancement_routes
from vera_web_v2_payroll_personal import install_payroll_personal_defaults, install_payroll_personal_routes
from vera_web_v2_payroll_saved_edit import install_payroll_saved_edit_routes
from vera_web_v2_payroll_timesoft_auto import install_payroll_timesoft_auto_routes
from vera_web_v2_payroll_v38 import PAYROLL_V38_RELEASE, install_payroll_v38_routes
from vera_web_v2_policy_v39 import install_policy_v39
from vera_web_v2_policy_v40 import install_policy_v40
from vera_web_v2_people import invalidate_tour_cache
from vera_web_v2_purchase_reconcile import install_purchase_reconcile_routes
from vera_web_v2_purchase_reconcile_alert_check import install_purchase_reconcile_alert_check
from vera_web_v2_purchase_reconcile_v2 import install_purchase_reconcile_v2
from vera_web_v2_revenue_leave_list import install_revenue_leave_list_routes
from vera_web_v2_revenue_report_target import install_revenue_report_target
from vera_web_v2_shift_break_admin import install_shift_break_admin_routes
from vera_web_v2_staff_security import install_staff_security_routes
from vera_web_v2_staff_status_sort import install_staff_status_sort
from vera_web_v2_support_shift_break import install_support_shift_break
from vera_web_v2_system_name import install_system_name_routes
from vera_web_v2_tour_leave_sync import install_tour_leave_sync_routes
from vera_web_v2_violation_unlimited import install_violation_unlimited
from vera_web_v2_work_schedule import install_work_schedule_routes
from vera_web_v2_work_schedule_permissions import install_work_schedule_permissions

_api = _shared._api
install_work_schedule_permissions()
install_payroll_personal_defaults(api_module=_api)
_audit_archive.identity_type = _api.Identity
_audit_archive.leave_update_type = _api.LeaveUpdate
_audit_archive.leave_delete_type = _api.LeaveDelete
_staff_sort.identity_type = _api.Identity

install_payroll_v38_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, norm=_api._norm, identity_type=_api.Identity, google_client=_api._google_client)
install_department_payroll_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity, norm=_api._norm)
install_payroll_timesoft_auto_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity, norm=_api._norm)
install_payroll_debt_sync_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity, google_client=_api._google_client)
install_payroll_enhancement_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, norm=_api._norm, identity_type=_api.Identity)
install_payroll_personal_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, identity_type=_api.Identity, norm=_api._norm)
install_accumulation_permission(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity, api_module=_api)
install_payroll_saved_edit_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, norm=_api._norm, identity_type=_api.Identity)
install_staff_security_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, norm=_api._norm, identity_type=_api.Identity)
install_staff_status_sort(_shared.app, current_identity=_api.current_identity, identity_type=_api.Identity)
install_shift_break_admin_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, identity_type=_api.Identity)
install_system_name_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, identity_type=_api.Identity)
install_tour_leave_sync_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity, google_client=_api._google_client, leave_sheet_id=_api.LEAVE_SHEET_ID, vn_tz=_api.VN_TZ, invalidate_tour_cache=invalidate_tour_cache)
install_leave_source_export_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity, norm=_api._norm, google_client=_api._google_client, leave_sheet_id=_api.LEAVE_SHEET_ID)
install_work_schedule_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, feature_allowed=_api._feature_allowed)
install_auto_check_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity)
install_policy_v39(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, vn_tz=_api.VN_TZ)
install_policy_v40(_shared.app, shared_module=_shared)
install_violation_unlimited(_shared.app, shared_module=_shared)
install_leave_day_stats_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, feature_allowed=_api._feature_allowed, daily_quota_config=_api._daily_quota_config, employee_name_matches=_api._employee_name_matches, norm=_api._norm, weekday_short_label=_api._weekday_short_label, identity_type=_api.Identity)
install_leave_violation_split_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, feature_allowed=_api._feature_allowed, policy_rows=_api._policy_rows, field=_api._field, reason_item=_api._reason_item, role_tokens=_api._role_tokens, day_allowed=_api._day_allowed, norm=_api._norm)
install_leave_preview_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, feature_allowed=_api._feature_allowed, validate_and_prepare=_shared._validate_and_prepare, identity_type=_api.Identity)
install_long_leave_admin_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, identity_type=_api.Identity, norm=_api._norm, google_client=_api._google_client, leave_sheet_id=_api.LEAVE_SHEET_ID, vn_tz=_api.VN_TZ, validate_and_prepare=_shared._validate_and_prepare, leave_create_type=_api.LeaveCreate, sheet_row_for_record=_api._sheet_row_for_record, insert_record=_api._insert_record)
install_admin_audit_archive_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity, leave_update_type=_api.LeaveUpdate, leave_delete_type=_api.LeaveDelete)
install_leave_sync_queue(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, validate_and_prepare=_shared._validate_and_prepare, identity_type=_api.Identity, api_module=_api)
install_letan_leave_guard(_shared.app, api_module=_api, vn_tz=_api.VN_TZ)
install_revenue_leave_list_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, feature_allowed=_api._feature_allowed, norm=_api._norm, progressive_key=_api._progressive_key, google_client=_api._google_client)
install_revenue_report_target(_shared.app, current_identity=_api.current_identity)
install_purchase_reconcile_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, norm=_api._norm, google_client=_api._google_client)
install_purchase_reconcile_v2(_shared.app, engine_instance=_api._engine_instance, api_module=_api, current_identity=_api.current_identity, identity_type=_api.Identity)
install_purchase_reconcile_alert_check(_shared.app, engine_instance=_api._engine_instance, api_module=_api, current_identity=_api.current_identity, identity_type=_api.Identity, norm=_api._norm, google_client=_api._google_client)

install_attendance_v42(_shared.app, engine_instance=_api._engine_instance)
install_department_attendance_routes(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, identity_type=_api.Identity)
install_attendance_break_window(_shared.app)
install_attendance_break_alerts(_shared.app, engine_instance=_api._engine_instance, api_module=_api, current_identity=_api.current_identity, identity_type=_api.Identity, vn_tz=_api.VN_TZ)
install_attendance_policy_patch()
install_outside_leave_rule(_shared.app, engine_instance=_api._engine_instance)
# Apply recognized Hỗ trợ-ca schedules to every employee after the full attendance
# chain is installed. This removes only false 'đi trễ' break restrictions.
install_support_shift_break(_shared.app, engine_instance=_api._engine_instance, snapshot_module=_snapshot)
install_break_alert_control(_shared.app, engine_instance=_api._engine_instance, api_module=_api, current_identity=_api.current_identity, identity_type=_api.Identity)
install_break_return_penalty(_shared.app, engine_instance=_api._engine_instance, api_module=_api, vn_tz=_api.VN_TZ)
install_attendance_break_dispatch(_shared.app, engine_instance=_api._engine_instance, api_module=_api, vn_tz=_api.VN_TZ)
install_operations_v41(_shared.app, engine_instance=_api._engine_instance, current_identity=_api.current_identity, require_feature=_api._require_feature, identity_type=_api.Identity)
install_admin_change_push(_shared.app, engine_instance=_api._engine_instance, api_module=_api, current_identity=_api.current_identity, identity_type=_api.Identity, leave_create_type=_api.LeaveCreate, leave_update_type=_api.LeaveUpdate, leave_delete_type=_api.LeaveDelete)
install_excel_export_style(_shared.app)

app = _shared.app
app.version = PAYROLL_V38_RELEASE
