const guides = {
 object:['Bấm Tùy chỉnh để bật chế độ chọn thành phần.','Chọn object, section, header hoặc text trên trang. Chọn khung cha để đi ra ngoài; Thành phần bên trong để chọn phần con.','Chỉnh kích thước, tên/nội dung, căn chỉnh và mở Phong cách & hiệu ứng để chỉnh màu/font/viền.','Bấm Lưu để áp dụng; Hủy để bỏ bản xem trước.'],
 'Tùy chỉnh':['Bấm Tùy chỉnh ở hàng đầu tiên.','Chọn thành phần bất kỳ trên trang, không cần chọn loại nút/tab trước.','Các thuộc tính hiện tại xuất hiện ngay trong bảng; chọn khung cha hoặc thành phần con khi cần.','Chỉnh rồi Lưu.'],
 'Tạm dùng bố cục mặc định':['Lưu hoặc hủy bản xem trước nếu đang sửa.','Bấm Mặc định ở hàng trên cùng và xác nhận để dùng giao diện mặc định toàn hệ thống.','Cấu hình đã lưu vẫn được giữ. Bấm Tiếp tục để áp dụng lại.'],
 'Tiếp tục':['Bấm Tiếp tục và xác nhận.','Hệ thống áp dụng lại bố cục đã lưu.','Mở Tùy chỉnh nếu cần sửa thêm.'],
 'Cỡ nút công cụ':['Kéo thanh sang trái để thu nhỏ các nút và khoảng cách trong bảng công cụ.','Kéo sang phải để tăng kích thước; có thể dùng phím mũi tên.','Cỡ này chỉ lưu trên trình duyệt hiện tại và không thay đổi nút trên website.','Cuộn trong bảng để đến các công cụ còn lại, hoặc kéo giãn bảng.'],
 'Sửa text':['Chọn text/box tự thêm hoặc nhãn menu/nút có thể đổi tên.','Bấm Sửa text để chuyển đến ô Nội dung hoặc Tên hiển thị.','Nhập văn bản và xem kết quả. Nội dung động như số tiền, tên nhân viên được sửa bằng chức năng nghiệp vụ tương ứng.','Bấm Lưu.'],
 'Lưu':['Kiểm tra loại cấu hình Desktop/Mobile đang chọn.','Quan sát trang, tên, kích thước và thành phần đã thêm/ẩn.','Bấm Lưu và chờ thông báo thành công.','Thiết bị khác nhận cấu hình trong khoảng một phút; nếu báo xung đột hãy tải lại cấu hình trước khi sửa tiếp.'],
 'Hủy':['Kiểm tra xem có thay đổi nào cần lưu trước không.','Bấm Hủy để bỏ toàn bộ bản xem trước đang sửa.','Cấu hình đã lưu vẫn được giữ; mở chỉnh sửa lại khi cần.'],
 'Mặc định':['Chọn đúng Desktop hoặc Mobile.','Bấm Mặc định và xác nhận để xóa tùy chỉnh của chế độ đó trong bản xem trước.','Kiểm tra kết quả; bấm Lưu để áp dụng hoặc Hủy để giữ bản cũ.'],
 'Khôi phục thành phần':['Chọn thành phần cần đặt lại.','Bấm Khôi phục thành phần để bỏ kiểu/kích thước/vị trí tùy chỉnh của nó.','Box/text tự thêm giữ nội dung; dùng Xóa box hoặc Xóa text nếu muốn bỏ hẳn.','Kiểm tra rồi Lưu.'],
 'Di chuyển bảng công cụ':['Giữ chuột hoặc chạm nút Di chuyển.','Kéo bảng sang vị trí mong muốn trong màn hình.','Thả để giữ vị trí trên trình duyệt này; phím mũi tên cũng di chuyển được.','Bấm Vị trí để khôi phục vị trí và kích thước mặc định.'],
 'Kéo đổi kích thước bảng công cụ':['Giữ nút kéo giãn ở cuối bảng điều khiển.','Kéo ngang để đổi rộng, dọc để đổi cao.','Thả để giữ kích thước; Esc hủy lượt kéo.','Dùng Vị trí nếu muốn trả bảng về mặc định.'],
 order:['Bấm Tùy chỉnh để bật chế độ sửa.','Chọn thành phần trên trang; viền chọn cho biết đối tượng đang chỉnh.','Kéo trong nhóm hoặc chọn Khung đích để chuyển giữa các nhóm tương thích. Dùng Trước/Sau để đổi thứ tự.','Bấm Lưu; Hủy để bỏ bản xem trước.'],
 buttons:['Bật chỉnh sửa rồi chọn một nút trên trang.','Bấm Chọn khung cha nếu cần chỉnh cả nhóm nút.','Chọn số dòng, cách gom nhóm hoặc cỡ chữ. Xem kết quả ngay trên trang.','Lưu khi bố trí đã phù hợp.'],
 labels:['Bật chỉnh sửa rồi chọn menu/tab/nút có nhãn cố định.','Nhấp đúp chữ hoặc sửa ô Tên hiển thị. Với text tự thêm, sửa ô Nội dung.','Enter xác nhận lần sửa trực tiếp; Escape hủy. Không nhập dữ liệu khách hàng vào nhãn dùng chung.','Bấm Lưu để áp dụng tên mới.'],
 style:['Bật chỉnh sửa và chọn thành phần cần trang trí.','Chọn trạng thái Bình thường/Rê chuột/Đang nhấn/Đang chọn/Focus.','Chọn màu, font, bóng hoặc Mẫu xanh 3D; chỉnh thông số và quan sát bản xem trước.','Xóa hiệu ứng để bỏ riêng kiểu trang trí; Lưu để áp dụng.'],
 columns:['Mở trang có bảng cần chỉnh.','Chọn cột và nhập độ rộng trong danh sách công cụ.','Kiểm tra bảng trên loại thiết bị đang mở.','Lưu độ rộng cột; cấu hình cột Live Tour dùng nút lưu trong phần riêng của nó.'],
 rooms:['Mở nhóm Phòng Live Tour.','Chọn cấu hình phòng/hiển thị cần thay đổi.','Điều chỉnh thông số trong biểu mẫu và kiểm tra bản xem trước nếu có.','Dùng nút lưu của phần Phòng Live Tour.'],
 history:['Chọn Desktop hoặc Mobile trong ô Chế độ giao diện.','Xem phiên bản, người lưu và thời gian trong danh sách.','Bấm Khôi phục ở phiên bản muốn dùng rồi xác nhận.','Bản khôi phục áp dụng cho loại thiết bị đó; cấu hình phòng/cột riêng quản lý ở mục tương ứng.'],
 elements:['Bấm Tùy chỉnh.','Chọn vị trí trên trang rồi bấm Thêm box hoặc Thêm text; nếu chưa chọn, thành phần xuất hiện cuối nội dung trang.','Chọn thành phần mới; sửa Nội dung, kéo góc đổi kích thước hoặc vào Hiệu ứng.','Xóa sẽ bỏ box/text tự thêm; Ẩn chỉ ẩn thành phần có sẵn. Lưu để áp dụng.'],
 'Thêm box':['Chọn thành phần làm mốc trên trang hoặc bỏ chọn để thêm cuối trang.','Bấm Thêm box. Một khung có viền xuất hiện sau mốc.','Nhập Nội dung; kéo góc hoặc nhập rộng/cao; chỉnh màu/viền trong Hiệu ứng.','Lưu. Box mới là phần trình bày, không tự tạo dữ liệu nghiệp vụ.'],
 'Thêm text':['Chọn thành phần làm mốc rồi bấm Thêm text.','Nhập văn bản trong ô Nội dung; nội dung hiển thị dạng chữ thuần.','Chỉnh font, màu, căn chữ và kích thước.','Lưu để người dùng thấy trên trang và loại thiết bị tương ứng.'],
 'Xóa / Ẩn':['Chọn thành phần cần bỏ khỏi giao diện.','Bấm Xóa box hoặc Xóa text hoặc Ẩn thành phần rồi xác nhận.','Kiểm tra bản xem trước; dùng Hiện lại cho phần bị ẩn hoặc Hủy để bỏ thay đổi.','Lưu. Dữ liệu nghiệp vụ không bị xóa; lịch sử cấu hình cho phép khôi phục.'],
 'Kích thước':['Chọn thành phần hoặc Chọn khung cha.','Xem kích thước đang hiển thị; kéo tay nắm góc phải dưới hoặc nhập rộng/cao.','Dùng phím mũi tên trên tay nắm để chỉnh 1px, Shift để chỉnh 10px; Esc hủy lượt kéo.','Chiều cao là tối thiểu để không cắt chữ. Lưu để giữ kích thước.'],
 'Chọn khung cha':['Chọn thành phần con trên trang.','Bấm Chọn khung cha để chọn khung bao ngoài gần nhất có thể chỉnh.','Kiểm tra dòng Đã chọn và thông số hiện tại trước khi thay đổi.','Chỉnh rộng/cao/căn nhóm/hiệu ứng rồi Lưu.'],
}
export default function LayoutToolGuide({ tab, tool }) {
 const normalizedTool = tool?.startsWith('Cỡ nút công cụ') ? 'Cỡ nút công cụ' : ['Xóa box','Xóa text','Xóa khỏi giao diện'].includes(tool) ? 'Xóa / Ẩn' : tool
 const steps=guides[normalizedTool] || guides[tab] || guides.object
 return <section className="layout-tool-guide" aria-label="Hướng dẫn công cụ"><strong>Hướng dẫn: {tool || ({object:'Thành phần',order:'Sắp xếp',buttons:'Nút bấm',labels:'Tên hiển thị',style:'Hiệu ứng',columns:'Bảng & cột',rooms:'Phòng Live Tour',history:'Lịch sử',elements:'Thêm / Xóa'})[tab]}</strong>
 {tool && !guides[normalizedTool] && <p>Chọn đối tượng, chỉnh “{tool}”, kiểm tra kết quả trên trang rồi lưu.</p>}<ol>{steps.map(step=><li key={step}>{step}</li>)}</ol></section>
}
