import UiToolbar from './UiToolbar'
import UiCustomText from './UiCustomText'
import { sortedTipCards, tipAmount, tipMoney } from '../lib/paymentPresentation'
import { useState } from 'react'
import { Plus, Save, Trash2 } from 'lucide-react'

export default function LiveTourPaymentSettings({ value, busy, onSave }) {
  const [form, setForm] = useState(() => ({ open_receipt: true, bank: { enabled: false, bank_id: '', account_no: '', account_name: '' }, ...structuredClone(value || { auto_print: false, tip_cards: [] }), tip_cards: sortedTipCards(value?.tip_cards) }))
  return <form className="tour-payment-settings" onSubmit={(event) => { event.preventDefault(); onSave({ ...form, auto_print: form.open_receipt && form.auto_print, tip_cards: sortedTipCards(form.tip_cards) }) }}><h3>Cài đặt thanh toán và in hóa đơn</h3>
    <label>Hiện nhân viên đang thực hiện khi còn dưới (phút)<input type="number" min="1" max="180" step="1" required disabled={busy} value={form.booking_available_minutes ?? 30} onChange={e => setForm(c => ({ ...c, booking_available_minutes: e.target.value === '' ? '' : Number(e.target.value) }))}/><small>Áp dụng trong danh sách nhân viên khi đặt booking. Nhân viên đang chờ vẫn được ẩn; danh sách tự cập nhật theo thời gian còn lại.</small></label>
    <fieldset disabled={busy}><legend>Quy định đổi nhân viên</legend>
      <label className="live-tour-check-field"><input type="checkbox" checked={form.employee_change_enabled !== false} onChange={e => setForm(c => ({ ...c, employee_change_enabled: e.target.checked }))}/> Kích hoạt tác vụ đổi nhân viên</label>
      <label>Cho phép đổi khi thời gian dịch vụ còn lại không quá (phút)<input type="number" min="1" max="180" step="1" required disabled={busy || form.employee_change_enabled === false} value={form.employee_change_minutes ?? 10} onChange={e => setForm(c => ({ ...c, employee_change_minutes: e.target.value === '' ? '' : Number(e.target.value) }))}/><small>Admin có thể đặt từ 1–180 phút. Khi tạm ngưng, hệ thống ẩn/chặn tác vụ ngay; ngưỡng mới có hiệu lực ngay cho cả các lượt đang thực hiện.</small></label>
    </fieldset>
    <fieldset disabled={busy}><legend>Đánh dấu nhân viên đã check-in trước giờ lên tua</legend><p>Ô tên có nền xanh lam trước giờ bên dưới, tự trở về màu trạng thái khi đến giờ. Booking trước các mốc giờ này tự gắn YC. Giờ Việt Nam, định dạng 24 giờ; 12:00 là buổi trưa.</p>{[['shift2', 'Ca 2', '13:00'], ['support1', 'Hỗ trợ Ca 1', '12:00'], ['support2', 'Hỗ trợ Ca 2', '14:00']].map(([key, label, fallback]) => <label key={key}>{label}<input type="time" required value={form.shift_ready_times?.[key] ?? fallback} onChange={event => setForm(current => ({ ...current, shift_ready_times: { shift2: '13:00', support1: '12:00', support2: '14:00', ...current.shift_ready_times, [key]: event.target.value } }))}/></label>)}</fieldset>
    <label className="live-tour-check-field"><input type="checkbox" aria-label="Mở hóa đơn sau thanh toán" disabled={busy} checked={form.open_receipt} onChange={e => setForm(current => ({ ...current, open_receipt: e.target.checked, auto_print: e.target.checked && current.auto_print }))}/> Mở hóa đơn sau thanh toán</label>
    <label className="live-tour-check-field"><input type="checkbox" aria-label="Tự động mở hộp thoại in sau thanh toán" disabled={busy || !form.open_receipt} checked={form.auto_print} onChange={(event) => setForm((current) => ({ ...current, auto_print: event.target.checked }))}/> Tự động mở hộp thoại in sau thanh toán (mặc định tắt)</label>
    <fieldset disabled={busy}><legend>Tài khoản ngân hàng mặc định</legend>
      <label><input type="checkbox" checked={form.bank.enabled} onChange={e => setForm(c => ({ ...c, bank: { ...c.bank, enabled: e.target.checked } }))}/> Hiển thị QR thanh toán</label>
      {[['bank_id', 'Mã ngân hàng / BIN', '[A-Za-z0-9]{2,20}'], ['account_no', 'Số tài khoản', '[0-9]{6,19}'], ['account_name', 'Tên chủ tài khoản', undefined]].map(([key, label, pattern]) => <label key={key}>{label}<input required={form.bank.enabled} pattern={pattern} value={form.bank[key]} onChange={e => setForm(c => ({ ...c, bank: { ...c.bank, [key]: e.target.value } }))}/></label>)}
      <small>Lễ tân mặc định dùng ngân hàng trong hồ sơ cá nhân; có thể chọn tài khoản này khi thanh toán. Mã ngân hàng: VCB, ACB hoặc BIN 970436.</small>
    </fieldset>
    <fieldset disabled={busy}><legend>Màn hình QR cho khách hàng</legend><label className="live-tour-check-field"><input type="checkbox" checked={form.customer_screen?.enabled === true} onChange={event => setForm(current => ({ ...current, customer_screen:{ width:420, height:600, qr_size:300, ...current.customer_screen, enabled:event.target.checked } }))}/> Cho phép mở QR trong cửa sổ riêng</label>{[['width','Chiều rộng cửa sổ',320,1200,420],['height','Chiều cao cửa sổ',400,1200,600],['qr_size','Kích thước mã QR',200,800,300]].map(([key,label,min,max,fallback]) => <label key={key}>{label} (px)<input type="number" min={min} max={max} required value={form.customer_screen?.[key] ?? fallback} onChange={event => setForm(current => ({ ...current, customer_screen:{ enabled:false,width:420,height:600,qr_size:300,...current.customer_screen,[key]:event.target.value === '' ? '' : Number(event.target.value) } }))}/></label>)}<small>Mở từ QR trên hóa đơn hoặc màn hình thanh toán, sau đó kéo cửa sổ sang màn hình phụ. QR cập nhật theo số tiền đang hiển thị; đóng hóa đơn sẽ đóng cửa sổ QR.</small></fieldset>
    <strong>Thẻ tiền TIP</strong>{form.tip_cards.map((card, index) => <div className="tour-payment-setting-row" key={card.id}><input aria-label={`Tên thẻ TIP ${index + 1}`} onBlur={() => setForm(c => ({ ...c, tip_cards: sortedTipCards(c.tip_cards.map(row => ({ ...row, name: row.amount === '' ? '' : tipMoney(row.amount) }))) }))} inputMode="numeric" required maxLength="80" disabled={busy} value={card.name} onChange={(event) => setForm((current) => ({ ...current, tip_cards: current.tip_cards.map(row => row.id === card.id ? { ...row, name: event.target.value, amount: event.target.value ? tipAmount(event.target.value) : '' } : row) }))}/><input aria-label={`Mệnh giá thẻ TIP ${index + 1}`} onBlur={() => setForm(c => ({ ...c, tip_cards: sortedTipCards(c.tip_cards.map(row => ({ ...row, name: row.amount === '' ? '' : tipMoney(row.amount) }))) }))} type="number" required min="1" max="10000000000" step="1" disabled={busy} value={card.amount} onChange={(event) => setForm((current) => ({ ...current, tip_cards: current.tip_cards.map(row => row.id === card.id ? { ...row, amount: event.target.value === '' ? '' : Number(event.target.value), name: event.target.value === '' ? '' : tipMoney(event.target.value) } : row) }))}/><button data-ui-key="u-2e1e2869508e" className="icon-button" type="button" disabled={busy} aria-label={`Xóa thẻ TIP ${index + 1}`} onClick={() => setForm((current) => ({ ...current, tip_cards: current.tip_cards.filter(row => row.id !== card.id) }))}><Trash2 size={16}/></button></div>)}
    <UiToolbar data-ui-key="u-2d0204de2072" className="live-tour-card-actions"><button data-ui-key="u-84499bd6fce6" data-ui-label-default="Thêm thẻ TIP" type="button" className="secondary-button" disabled={busy || form.tip_cards.length >= 30} onClick={() => setForm((current) => ({ ...current, tip_cards: [...current.tip_cards, { id: crypto.randomUUID(), name: '', amount: '' }] }))}><Plus size={15}/><UiCustomText uiKey="u-84499bd6fce6"> Thêm thẻ TIP</UiCustomText></button><button data-ui-key="u-77c209463246" data-ui-label-default="Lưu cài đặt thanh toán" type="submit" className="primary-button" disabled={busy}><Save size={15}/><UiCustomText uiKey="u-77c209463246"> Lưu cài đặt thanh toán</UiCustomText></button></UiToolbar>
  </form>
}
