import { sortedTipCards, tipAmount, tipMoney } from '../lib/paymentPresentation'
import { useState } from 'react'
import { Plus, Save, Trash2 } from 'lucide-react'

export default function LiveTourPaymentSettings({ value, busy, onSave }) {
  const [form, setForm] = useState(() => ({ open_receipt: true, bank: { enabled: false, bank_id: '', account_no: '', account_name: '' }, ...structuredClone(value || { auto_print: false, tip_cards: [] }), tip_cards: sortedTipCards(value?.tip_cards) }))
  return <form className="tour-payment-settings" onSubmit={(event) => { event.preventDefault(); onSave({ ...form, auto_print: form.open_receipt && form.auto_print, tip_cards: sortedTipCards(form.tip_cards) }) }}><h3>Cài đặt thanh toán và in hóa đơn</h3>
    <label>Thời hạn đổi nhân viên (phút đầu)<input type="number" min="1" max="180" step="1" required disabled={busy} value={form.employee_change_minutes ?? 10} onChange={e => setForm(c => ({ ...c, employee_change_minutes: Number(e.target.value) }))}/><small>Áp dụng cho các lượt bắt đầu sau khi lưu.</small></label>
    <label className="live-tour-check-field"><input type="checkbox" disabled={busy} checked={form.open_receipt} onChange={e => setForm(current => ({ ...current, open_receipt: e.target.checked, auto_print: e.target.checked && current.auto_print }))}/> Mở hóa đơn sau thanh toán</label>
    <label className="live-tour-check-field"><input type="checkbox" disabled={busy || !form.open_receipt} checked={form.auto_print} onChange={(event) => setForm((current) => ({ ...current, auto_print: event.target.checked }))}/> Tự động mở hộp thoại in sau thanh toán (mặc định tắt)</label>
    <fieldset disabled={busy}><legend>Tài khoản ngân hàng mặc định</legend>
      <label><input type="checkbox" checked={form.bank.enabled} onChange={e => setForm(c => ({ ...c, bank: { ...c.bank, enabled: e.target.checked } }))}/> Hiển thị QR thanh toán</label>
      {[['bank_id', 'Mã ngân hàng / BIN', '[A-Za-z0-9]{2,20}'], ['account_no', 'Số tài khoản', '[0-9]{6,19}'], ['account_name', 'Tên chủ tài khoản', undefined]].map(([key, label, pattern]) => <label key={key}>{label}<input required={form.bank.enabled} pattern={pattern} value={form.bank[key]} onChange={e => setForm(c => ({ ...c, bank: { ...c.bank, [key]: e.target.value } }))}/></label>)}
      <small>Lễ tân mặc định dùng ngân hàng trong hồ sơ cá nhân; có thể chọn tài khoản này khi thanh toán. Mã ngân hàng: VCB, ACB hoặc BIN 970436.</small>
    </fieldset>
    <strong>Thẻ tiền TIP</strong>{form.tip_cards.map((card, index) => <div className="tour-payment-setting-row" key={card.id}><input aria-label={`Tên thẻ TIP ${index + 1}`} onBlur={() => setForm(c => ({ ...c, tip_cards: sortedTipCards(c.tip_cards.map(row => ({ ...row, name: row.amount === '' ? '' : tipMoney(row.amount) }))) }))} inputMode="numeric" required maxLength="80" disabled={busy} value={card.name} onChange={(event) => setForm((current) => ({ ...current, tip_cards: current.tip_cards.map(row => row.id === card.id ? { ...row, name: event.target.value, amount: event.target.value ? tipAmount(event.target.value) : '' } : row) }))}/><input aria-label={`Mệnh giá thẻ TIP ${index + 1}`} onBlur={() => setForm(c => ({ ...c, tip_cards: sortedTipCards(c.tip_cards.map(row => ({ ...row, name: row.amount === '' ? '' : tipMoney(row.amount) }))) }))} type="number" required min="1" max="10000000000" step="1" disabled={busy} value={card.amount} onChange={(event) => setForm((current) => ({ ...current, tip_cards: current.tip_cards.map(row => row.id === card.id ? { ...row, amount: event.target.value === '' ? '' : Number(event.target.value), name: event.target.value === '' ? '' : tipMoney(event.target.value) } : row) }))}/><button className="icon-button" type="button" disabled={busy} aria-label={`Xóa thẻ TIP ${index + 1}`} onClick={() => setForm((current) => ({ ...current, tip_cards: current.tip_cards.filter(row => row.id !== card.id) }))}><Trash2 size={16}/></button></div>)}
    <div className="live-tour-card-actions"><button type="button" className="secondary-button" disabled={busy || form.tip_cards.length >= 30} onClick={() => setForm((current) => ({ ...current, tip_cards: [...current.tip_cards, { id: crypto.randomUUID(), name: '', amount: '' }] }))}><Plus size={15}/> Thêm thẻ TIP</button><button type="submit" className="primary-button" disabled={busy}><Save size={15}/> Lưu cài đặt thanh toán</button></div>
  </form>
}
