import test from 'node:test'
import { readFileSync } from 'node:fs'
const registry = JSON.parse(readFileSync(new URL('../../vera_ui_registry.json', import.meta.url)))
const labelKey = Object.keys(registry).find(key => registry[key].tag === 'button' && registry[key].label && !registry[key].locked)
import assert from 'node:assert/strict'
import { build } from 'esbuild'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import React, { act } from 'react'
import { JSDOM } from 'jsdom'

const built = await build({ entryPoints: [fileURLToPath(new URL('../src/components/LayoutDesigner.jsx', import.meta.url))], bundle: true, write: false, platform: 'node', format: 'cjs', jsx: 'automatic', external: ['react', 'react/jsx-runtime'], loader: { '.css': 'empty' }, plugins: [{ name: 'api', setup(b) {
  b.onResolve({ filter: /\/lib\/api$/ }, () => ({ path: 'api', namespace: 'fixture' }))
  b.onLoad({ filter: /.*/, namespace: 'fixture' }, () => ({ contents: 'export const veraApi=globalThis.__layoutApi', loader: 'js' }))
} }] })

test('Admin drags within a group, saves desktop only, and another user receives the layout without edit controls', async () => {
  const dom = new JSDOM('<body><div id="root"></div></body>', { pretendToBeVisual: true, url:'https://test.invalid' })
  const names = ['window','document','navigator','getComputedStyle','MutationObserver','localStorage','IS_REACT_ACT_ENVIRONMENT','__layoutApi']
  const previous = Object.fromEntries(names.map(key => [key, Object.getOwnPropertyDescriptor(globalThis, key)]))
  for (const key of ['window','document','navigator','getComputedStyle','MutationObserver','localStorage']) Object.defineProperty(globalThis,key,{ value: key === 'window' ? dom.window : dom.window[key], configurable:true })
  globalThis.IS_REACT_ACT_ENVIRONMENT = true
  let server = { revision: 0, layout: { desktop: {}, mobile: { 'l-mobile': { width: 80 } } } }, actionCalls = 0
  const writes = []
  globalThis.__layoutApi = { uiLayout: async () => structuredClone(server), saveUiLayout: async body => { writes.push(body); server = { revision: 1, layout: { ...server.layout, [body.device]: body.items } }; return structuredClone(server) } }
  const module = { exports: {} }
  new Function('require','module','exports',built.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports)
  const Designer = module.exports.default
  const { createRoot } = await import('react-dom/client')
  const root = createRoot(document.querySelector('#root'))
  let closeCalls = 0
  const screen = (role, open = false) => React.createElement('div', { className:'app-shell' }, React.createElement('nav',{ className:'page-content','data-vera-node':'nav',style:{display:'flex'} }, ['first','second'].map(id => React.createElement('button',{ key:id, id,'data-ui-key':id === 'first' ? labelKey : undefined,'data-vera-node':'button','data-vera-item':id,onClick:()=>actionCalls++ },id))),React.createElement(Designer,{user:{role},page:'settings',open,onClose:()=>{closeCalls++;root.render(screen(role,false))}}))
  const click = async text => act(async () => [...document.querySelectorAll('.layout-designer button')].find(el=>el.textContent.includes(text)).click())
  try {
    await act(async()=>root.render(screen('admin')))
    assert.equal(document.querySelector('.layout-designer'),null,'closed by default')
    await act(async()=>root.render(screen('admin',true)))
    const topbar=document.querySelector('.layout-panel-frame-toolbar')
    assert.deepEqual([...topbar.querySelectorAll('button')].map(node=>node.textContent), ['Tùy chỉnh','Thành phần','Mặc định','Vị trí','Di chuyển','Hide'])
    assert.equal([...topbar.querySelectorAll('button')].find(node=>node.textContent==='Thành phần').getAttribute('aria-pressed'),'true')
    assert.equal([...document.querySelectorAll('button')].some(node=>node.textContent==='Lịch sử'),false)
    await click('Hide')
    assert.equal(document.querySelector('.layout-panel-content').hidden,true)
    await click('Show')
    assert.equal(document.querySelector('.layout-panel-content').hidden,false)
    assert.ok(![...document.querySelectorAll('[role="tab"]')].some(node=>['Nút bấm','Tên hiển thị','Bảng & cột'].includes(node.textContent)))
    const panel=document.querySelector('.layout-designer')
    const scale=document.querySelector('[aria-label="Cỡ nút công cụ"]')
    await act(()=>{Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set.call(scale,'70');scale.dispatchEvent(new window.Event('input',{bubbles:true}))})
    assert.equal(localStorage.getItem('vera-layout-tool-scale-v1'),'70')
    assert.equal(panel.style.getPropertyValue('--layout-tool-height'),'28px')
    assert.equal(writes.length,0,'tool density never saves page layout')
    panel.getBoundingClientRect=()=>({width:360,height:500,left:10,top:10})
    await act(()=>document.querySelector('[aria-label="Di chuyển bảng công cụ"]').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true})))
    assert.equal(JSON.parse(localStorage.getItem('vera-layout-panel-frame-v1')).left,15)
    await act(()=>document.querySelector('[aria-label="Kéo đổi kích thước bảng công cụ"]').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,shiftKey:true})))
    assert.equal(JSON.parse(localStorage.getItem('vera-layout-panel-frame-v1')).width,380)
    await click('Tùy chỉnh')
    await act(async()=>document.querySelector('.layout-free-mode input').click())
    const first=document.querySelector('#first'), second=document.querySelector('#second')
    document.elementFromPoint=()=>second
    await act(()=>first.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:1,clientY:1})))
    await act(()=>first.click())
    assert.equal(actionCalls,0,'editing must not trigger business actions')
    await act(()=>document.dispatchEvent(new window.MouseEvent('pointerup',{bubbles:true,clientX:100,clientY:1})))
    await click('Lưu')
    assert.equal(writes.length,1)
    assert.equal(writes[0].device,'desktop')
    assert.equal(writes[0].items[first.dataset.layoutKey].order,1)
    assert.equal(writes[0].items[second.dataset.layoutKey].order,0)
    assert.deepEqual(server.layout.mobile,{'l-mobile':{width:80}})
    await click('Tùy chỉnh')
    await act(async()=>document.querySelector('.layout-free-mode input').click())
    first.getBoundingClientRect=()=>({left:100,top:100,right:160,bottom:130,width:60,height:30})
    await act(async()=>first.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:110,clientY:110})))
    await act(async()=>document.dispatchEvent(new window.MouseEvent('pointermove',{bubbles:true,clientX:190,clientY:150,altKey:true})))
    assert.ok(document.querySelector('.layout-guide-horizontal'))
    assert.ok(document.querySelector('.layout-guide-vertical'))
    await act(async()=>document.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})))
    assert.equal(document.querySelector('.layout-alignment-guides'),null)
    assert.doesNotMatch(document.querySelector('style').textContent,/translate:80px 40px/)
    await act(async()=>first.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:110,clientY:110})))
    await act(async()=>document.dispatchEvent(new window.MouseEvent('pointerup',{bubbles:true,clientX:190,clientY:150,altKey:true})))
    await click('Lưu')
    assert.equal(writes.at(-1).items[first.dataset.layoutKey].offset_x,80)
    assert.equal(writes.at(-1).items[first.dataset.layoutKey].offset_y,40)
    assert.deepEqual(server.layout.mobile,{'l-mobile':{width:80}})
    // Drop into another registered row: insertion resets free offsets and persists order.
    await click('Tùy chỉnh')
    const groupKey=Object.keys(registry).find(key=>registry[key].group && !registry[key].locked)
    const destination=document.createElement('div'),peer=document.createElement('button')
    destination.dataset.uiDropzone=groupKey;destination.dataset.layoutKey=groupKey
    peer.dataset.uiOrigin=groupKey;peer.dataset.layoutKey='l-peer';peer.dataset.uiKey='l-peer'
    peer.getBoundingClientRect=()=>({left:200,top:250,right:260,bottom:280,width:60,height:30})
    destination.append(peer);document.querySelector('.app-shell').append(destination)
    first.dataset.uiOrigin='u-source';document.elementFromPoint=()=>peer
    await act(async()=>first.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:110,clientY:110})))
    await act(async()=>document.dispatchEvent(new window.MouseEvent('pointermove',{bubbles:true,clientX:205,clientY:255})))
    assert.ok(document.querySelector('.layout-drop-line'))
    await act(async()=>document.dispatchEvent(new window.MouseEvent('pointerup',{bubbles:true,clientX:205,clientY:255})))
    await click('Lưu')
    assert.equal(writes.at(-1).items[first.dataset.layoutKey].move_to,groupKey)
    assert.equal(writes.at(-1).items[first.dataset.layoutKey].offset_x,0)
    assert.equal(writes.at(-1).items[first.dataset.layoutKey].order,0)
    assert.equal(writes.at(-1).items['l-peer'].order,1)
    destination.remove();delete first.dataset.uiOrigin;document.elementFromPoint=()=>second
    await click('Tùy chỉnh')
    await act(()=>first.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:1,clientY:1})))
    document.querySelector('.layout-inspector-section').open=true
    await click('Mẫu xanh 3D')
    assert.match(document.querySelector('style').textContent,/linear-gradient/)
    await click('Lưu')
    assert.equal(writes.at(-1).items[labelKey].appearance.depth,3)
    assert.deepEqual(server.layout.mobile,{'l-mobile':{width:80}})
    await click('Tùy chỉnh')
    await act(()=>first.dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true})))
    let editor=document.querySelector('[aria-label="Sửa tên trực tiếp"]')
    assert.ok(editor)
    editor.value='Tên mới'
    await act(()=>editor.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})))
    assert.equal(document.querySelector('[aria-label="Sửa tên trực tiếp"]'),null)
    await act(()=>first.dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true})))
    editor=document.querySelector('[aria-label="Sửa tên trực tiếp"]')
    editor.value='Tên dùng chung'
    await act(()=>editor.blur())
    await click('Lưu')
    assert.equal(writes.at(-1).items[labelKey].label,'Tên dùng chung')
    assert.equal(actionCalls,0)
    assert.deepEqual(server.layout.mobile,{'l-mobile':{width:80}})
    await click('Tùy chỉnh')
    await click('Thêm text')
    await act(()=>new Promise(resolve=>setTimeout(resolve,50)))
    const custom=document.querySelector('.layout-custom-text')
    assert.ok(custom)
    assert.equal(document.querySelector('textarea').value,'Nội dung mới')
    await click('Sửa text')
    assert.equal(document.activeElement,document.querySelector('textarea'))
    await act(()=>{Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value').set.call(document.querySelector('textarea'),'Vera Spa mới');document.querySelector('textarea').dispatchEvent(new window.Event('input',{bubbles:true}))})
    assert.equal(document.querySelector('.layout-custom-text').textContent,'Vera Spa mới')
    await click('Lưu')
    const customKey=Object.keys(writes.at(-1).items).find(key=>key.startsWith('l-custom-'))
    assert.equal(writes.at(-1).items[customKey].custom_kind,'text')
    await click('Tùy chỉnh')
    document.querySelector('.app-shell').append(destination);document.elementFromPoint=()=>peer
    await act(async()=>custom.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:1,clientY:1})))
    await act(async()=>document.dispatchEvent(new window.MouseEvent('pointerup',{bubbles:true,clientX:205,clientY:255})))
    assert.ok(destination.querySelector('.layout-custom-text'),'custom text moves into the destination row')
    await click('Lưu')
    assert.equal(writes.at(-1).items[customKey].move_to,groupKey)
    await click('Tùy chỉnh')
    const movedCustom=destination.querySelector('.layout-custom-text')
    await act(()=>movedCustom.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:1,clientY:1})))
    window.confirm=()=>true
    await click('Xóa text')
    assert.equal(document.querySelector('.layout-custom-text'),null)
    await click('Lưu')
    assert.equal(writes.at(-1).items[customKey],undefined)
    destination.remove();document.elementFromPoint=()=>second
    await click('Tùy chỉnh')
    await click('Thêm box')
    await act(()=>new Promise(resolve=>setTimeout(resolve,50)))
    assert.ok(document.querySelector('.layout-custom-box'))
    await click('Xóa box')
    assert.equal(document.querySelector('.layout-custom-box'),null)
    // Parent/descendant navigation exposes one inspector, without changing tool tabs.
    await act(()=>first.dispatchEvent(new window.MouseEvent('pointerdown',{bubbles:true,clientX:1,clientY:1})))
    await click('Chọn khung cha')
    const descendants=document.querySelector('[aria-label="Thành phần bên trong"]')
    assert.ok(descendants)
    assert.ok([...document.querySelectorAll('label')].some(node=>node.textContent.startsWith('Phân bố nhóm')))
    await act(()=>{descendants.value=first.dataset.layoutKey;descendants.dispatchEvent(new window.Event('change',{bubbles:true}))})
    assert.ok(document.querySelector('input[maxlength="100"]'),'label editing stays available after selecting child')
    await click('Hủy')
    await click('Đóng')
    assert.equal(closeCalls,1)
    assert.equal(document.querySelector('.layout-designer'),null)
    await act(()=>first.click())
    assert.equal(actionCalls,1,'closing restores business clicks')
    Object.defineProperty(window,'innerWidth',{value:390,configurable:true})
    await act(()=>window.dispatchEvent(new window.Event('resize')))
    await act(async()=>root.render(screen('admin',true)))
    assert.equal(document.querySelector('[aria-label="Desktop"]').checked,true)
    await click('Đóng')
    assert.equal(document.querySelector('.layout-designer'),null)
    Object.defineProperty(window,'innerWidth',{value:1024,configurable:true})
    await act(()=>window.dispatchEvent(new window.Event('resize')))
    window.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}})
    await act(()=>window.dispatchEvent(new window.Event('resize')))
    await act(async()=>root.render(screen('admin',true)))
    assert.equal(document.querySelector('[aria-label="Desktop"]').checked,true,'Desktop remains default on resize and touch screens')
    await act(async()=>root.render(screen('nhanvien',true)))
    assert.equal(document.querySelector('.layout-designer'),null)
    assert.match(document.querySelector('style').textContent,/order:1!important/)
  } finally {
    await act(()=>root.unmount());dom.window.close()
    for(const [key,value]of Object.entries(previous)){if(value)Object.defineProperty(globalThis,key,value);else delete globalThis[key]}
  }
})
